# Generated by Django 3.0.2 on 2020-02-06 20:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, unique=True)),
                ('slug', models.SlugField()),
                ('parent_cat', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='classifier.Category')),
            ],
            options={
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, unique=True)),
                ('slug', models.SlugField(max_length=32, unique=True)),
            ],
            options={
                'verbose_name_plural': 'Cities',
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256)),
                ('desc', models.TextField()),
                ('price', models.IntegerField(blank=True, default=0)),
                ('status', models.IntegerField(choices=[(1, 'approved'), (2, 'rejected'), (3, 'pending')], default=3)),
                ('is_published', models.BooleanField(blank=True, default=0)),
                ('main_image', models.ImageField(upload_to='photos/%Y/%m/')),
                ('image_1', models.ImageField(blank=True, upload_to='photos/%Y/%m/')),
                ('image_2', models.ImageField(blank=True, upload_to='photos/%Y/%m/')),
                ('image_3', models.ImageField(blank=True, upload_to='photos/%Y/%m/')),
                ('image_4', models.ImageField(blank=True, upload_to='photos/%Y/%m/')),
                ('image_5', models.ImageField(blank=True, upload_to='photos/%Y/%m/')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='classifier.Category')),
                ('city', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='classifier.City')),
                ('profile', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='account.Profile')),
            ],
        ),
    ]
