# Generated by Django 3.0.2 on 2020-02-06 20:19

import account.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(editable=False, max_length=64)),
                ('profile_image', models.ImageField(blank=True, default='profiles/default.jpg', upload_to=account.models._user_profile_path)),
                ('phone', models.CharField(blank=True, max_length=10, null=True)),
                ('status', models.IntegerField(choices=[(1, 'pending'), (2, 'approved'), (3, 'rejected'), (4, 'inactive'), (5, 'banned')], default=2)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
